(() => {
  "use strict";
  const C = window.THREEB_START_CONFIG, KEY = "3b-canonical-west-v2";
  const bands = ["west","noord","oost","zuid"];
  const T = {
    en:{localConfig:"local work configuration",title:"3B line configurator",subtitle:"Enter diamond values and view the complete route immediately.",language:"Language",tables:"Tables",editTable:"Edit table",name:"Name",direction:"Direction",departure:"Departure",import:"Import",clear:"Clear name",screenConfig:"On-screen configuration",part:"Part",from:"V · departure",to:"A · arrival",rail:"Rail",value:"Value",display:"Live display",footer:"All points are line points on the four diamond lines · the cushion edge is not a measuring line · data stays in this browser",saved:"Saved locally",large:"Large",small:"Small",both:"Both",west:"West",east:"East — mirrored",nose:"Nose",head:"Head",lines:"parts",complete:"Complete route",empty:"Enter V and A to draw parts",help:"Long diamond lines: 0–80. Short diamond lines: 0–40. The selected departure starts at Z. Decimals are allowed.",out:"value outside rail range",confirm:"Clear",myTables:"My tables"},
    nl:{localConfig:"lokale werkconfig",title:"3B lijnconfigurator",subtitle:"Vul stipwaarden in en bekijk de volledige loop direct.",language:"Taal",tables:"Tafels",editTable:"Bewerk tafel",name:"Naam",direction:"Richting",departure:"Vertreklijn",import:"Importeer",clear:"Wis naam",screenConfig:"On-screen config",part:"Deel",from:"V · vertrek",to:"A · aankomst",rail:"Band",value:"Waarde",display:"Directe weergave",footer:"Alle punten zijn lijnpunten op de vier stiplijnen · de bandrand is geen rekenlijn · gegevens blijven in deze browser",saved:"Lokaal opgeslagen",large:"Groot",small:"Klein",both:"Beide",west:"West",east:"Oost — gespiegeld",nose:"Neus",head:"Kop",lines:"delen",complete:"Volledige loop",empty:"Vul V en A in om delen te tekenen",help:"Lange stiplijnen: 0–80. Korte stiplijnen: 0–40. De gekozen vertreklijn start bij Z. Decimalen zijn toegestaan.",out:"waarde buiten bandbereik",confirm:"Wis",myTables:"Mijn tafels"}
  };
  const $ = id => document.getElementById(id), copy = v => JSON.parse(JSON.stringify(v));
  function blank(){const p={};C.parts.forEach((l,i)=>{const fixed=C.fixedPartBands[l.key];p[l.key]=i===0?{from:{kind:"acquit",value:"Z"},to:{band:fixed.to,value:null}}:{from:{band:fixed.from,value:null},to:{band:fixed.to,value:null}};});return p;}
  function initial(){const d={};Object.keys(C.tables).forEach(t=>{d[t]={};C.shotLines.forEach(n=>{d[t][n]=blank();Object.assign(d[t][n],copy(C.defaults[t]?.[n]||{}));});});return {version:10,model:"canonical-west-v2",data:d,departurePositions:{},appliedMigrations:["small-five-tail-default-v19"],ui:{language:C.defaultLanguage,tableMode:C.defaultTableMode,editTable:"groot",pattern:"VIJF",direction:C.defaultDirection,departure:C.defaultDeparture,correctionMode:C.shortenedFourCushionCorrection.defaultMode,valueStyle:C.drawing.valueLabels.defaultMode,ballColor:C.drawing.balls.defaultColor,ballMarking:C.drawing.balls.defaultMarking,playRange:"lkl",lineOneMode:C.lineOneVariants.defaultMode,parallelOffset:C.lineOneVariants.parallel.defaultOffset,fanLine:C.lineOneVariants.fan.entries[0].key}};}
  function load(){try{const x=JSON.parse(localStorage.getItem(KEY));if([4,5,6,7,8,9,10].includes(x?.version)&&x.data){x.version=10;return x;}}catch(_){}return initial();}
  const state=load();let ui=state.ui,dragModels={},selectedBall=null;
  function normalize(){
    const base=initial();Object.keys(C.tables).forEach(t=>{state.data[t]??={};C.shotLines.forEach(n=>{state.data[t][n]??=base.data[t][n];C.parts.forEach(l=>state.data[t][n][l.key]??=base.data[t][n][l.key]);});});
    state.appliedMigrations??=[];if(!state.appliedMigrations.includes("small-five-tail-default-v19")){const five=state.data.klein?.VIJF,allZero=five&&[five.kruis?.from,five.kruis?.to,five.been?.from,five.been?.to].every(p=>Number(p?.value)===0);if(allZero){five.kruis=copy(C.defaults.klein.VIJF.kruis);five.been=copy(C.defaults.klein.VIJF.been);}state.appliedMigrations.push("small-five-tail-default-v19");}
    Object.keys(C.tables).forEach(t=>C.shotLines.forEach(n=>C.parts.forEach(part=>{const segment=state.data[t][n][part.key],fixed=C.fixedPartBands[part.key],zone=C.partPointZones?.[part.key]?.to;if(part.key!=="neus")segment.from.band=fixed.from;if(zone){const allowed=zone.canonicalPath.map(x=>x.band);if(!allowed.includes(segment.to.band))segment.to=copy(zone.defaultPoint);}else segment.to.band=fixed.to;["from","to"].forEach(side=>{if(Number.isFinite(Number(segment[side].value)))segment[side].value=Math.round(Number(segment[side].value));});})));
    ui.language=["en","nl"].includes(ui.language)?ui.language:"en"; ui.tableMode=["groot","klein","beide"].includes(ui.tableMode)?ui.tableMode:"groot"; ui.editTable=["groot","klein"].includes(ui.editTable)?ui.editTable:(ui.tableMode==="klein"?"klein":"groot");
    ui.pattern=C.shotLines.includes(ui.pattern)?ui.pattern:"VIJF";ui.direction=["west","oost"].includes(ui.direction)?ui.direction:"west";ui.departure=["neus","kop"].includes(ui.departure)?ui.departure:"neus";ui.correctionMode=C.shortenedFourCushionCorrection.modes.includes(ui.correctionMode)?ui.correctionMode:C.shortenedFourCushionCorrection.defaultMode;ui.valueStyle=C.drawing.valueLabels.modes.includes(ui.valueStyle)?ui.valueStyle:C.drawing.valueLabels.defaultMode;ui.playRange=["lkl","vrij"].includes(ui.playRange)?ui.playRange:"lkl";
    ui.lineOneMode=C.lineOneVariants.modes.includes(ui.lineOneMode)?ui.lineOneMode:C.lineOneVariants.defaultMode;ui.parallelOffset=Math.max(C.lineOneVariants.parallel.minimumOffset,Math.min(C.lineOneVariants.parallel.maximumOffset,Math.round(Number(ui.parallelOffset)||0)));ui.fanLine=C.lineOneVariants.fan.entries.some(x=>x.key===ui.fanLine)?ui.fanLine:C.lineOneVariants.fan.entries[0].key;
    ui.ballColor=C.drawing.balls.colors[ui.ballColor]?ui.ballColor:C.drawing.balls.defaultColor;ui.ballMarking=C.drawing.balls.markings.includes(ui.ballMarking)?ui.ballMarking:C.drawing.balls.defaultMarking;state.departurePositions??={};
  }
  function save(){state.ui=ui;localStorage.setItem(KEY,JSON.stringify(state));$("saveState").textContent=T[ui.language].saved;}
  function tr(k){return T[ui.language][k]||k;} function tableLabel(k){return C.tables[k].labels[ui.language];} function patternLabel(k){return C.patternLabels[k][ui.language];} function lineLabel(l){return l.labels[ui.language];}
  function mirror(b){return b==="west"?"oost":b==="oost"?"west":b;} function shownBand(b){return ui.direction==="oost"?mirror(b):b;} function storedBand(b){return ui.direction==="oost"?mirror(b):b;}
  function activeLines(){return C.parts.slice(ui.departure==="kop"?1:0);} function data(t=ui.editTable){return state.data[t][ui.pattern];}
  function signedOffset(n){return n===0?"0":`${n>0?"+":"−"}${Math.abs(n)}`;}
  function zLabel(n){return n===0?"Z":`Z${signedOffset(n)}`;}
  function lineOneName(){if(ui.lineOneMode==="parallel"&&ui.parallelOffset)return `${patternLabel(ui.pattern)}${signedOffset(ui.parallelOffset)}`;if(ui.lineOneMode==="waaier"){const f=C.lineOneVariants.fan.entries.find(x=>x.key===ui.fanLine);return f?.labels[ui.language]||ui.fanLine;}return patternLabel(ui.pattern);}
  function parallelBounds(t=ui.editTable){const rule=C.lineOneVariants.parallel,line=activeLines()[0],value=Number(data(t)[line.key].to.value),band=data(t)[line.key].to.band,railMax=(band==="west"||band==="oost")?80:40;if(!Number.isFinite(value))return{minimum:0,maximum:0};return{minimum:Math.max(rule.minimumOffset,Math.ceil(-value/rule.longRailUnitsPerStep)),maximum:Math.min(rule.maximumOffset,Math.floor((railMax-value)/rule.longRailUnitsPerStep))};}
  function adjustParallel(delta){const bounds=parallelBounds();ui.parallelOffset=Math.max(bounds.minimum,Math.min(bounds.maximum,ui.parallelOffset+delta));save();render();}
  function variantSegment(t,line,index){const seg=copy(data(t)[line.key]);if(index!==0||ui.lineOneMode==="basis")return seg;
    if(ui.lineOneMode==="parallel"){
      const step=C.lineOneVariants.parallel.longRailUnitsPerStep,maximum=(seg.to.band==="west"||seg.to.band==="oost")?80:40;
      if(Number.isFinite(Number(seg.to.value)))seg.to.value=Math.max(0,Math.min(maximum,Number(seg.to.value)+ui.parallelOffset*step));
      seg.from={kind:"acquit",value:zLabel(ui.parallelOffset),offset:ui.parallelOffset};return seg;
    }
    const fan=C.lineOneVariants.fan.entries.find(x=>x.key===ui.fanLine),a=state.data[t]?.[fan?.between?.[0]]?.[line.key],b=state.data[t]?.[fan?.between?.[1]]?.[line.key];
    seg.from={kind:"acquit",value:"Z",offset:0};
    if(fan&&a?.to?.band===b?.to?.band&&Number.isFinite(Number(a.to.value))&&Number.isFinite(Number(b.to.value)))seg.to={band:a.to.band,value:Number(a.to.value)+(Number(b.to.value)-Number(a.to.value))*fan.fraction};
    else seg.to.value=null;
    return seg;
  }
  function init(){normalize();bind();render();}
  function bind(){
    [["languageSelect","language"],["tableMode","tableMode"],["editTable","editTable"],["patternSelect","pattern"],["lineOneMode","lineOneMode"],["fanSelect","fanLine"],["noseDirection","direction"],["departureLine","departure"],["correctionMode","correctionMode"],["valueStyle","valueStyle"],["ballColor","ballColor"],["ballMarking","ballMarking"],["playRange","playRange"]].forEach(([id,key])=>$(id).addEventListener("change",e=>{ui[key]=e.target.value;if(key==="tableMode"&&ui.tableMode!=="beide")ui.editTable=ui.tableMode;if((key==="lineOneMode"&&ui.lineOneMode==="waaier")||key==="fanLine"){const fan=C.lineOneVariants.fan.entries.find(x=>x.key===ui.fanLine);if(fan)ui.pattern=fan.between[0];}save();render();}));
    $("exportSvg").onclick=exportSvg;$("exportJson").onclick=exportJson;$("importJson").onchange=importJson;$("resetPattern").onclick=reset;$("strokeMinus").onclick=()=>adjustStroke(-C.drawing.departureBall.precisionStepCm);$("strokePlus").onclick=()=>adjustStroke(C.drawing.departureBall.precisionStepCm);
    $("parallelMinus").onclick=()=>adjustParallel(-1);$("parallelPlus").onclick=()=>adjustParallel(1);
    document.querySelectorAll("[data-nudge]").forEach(button=>button.onclick=()=>nudgeSelected(Number(button.dataset.nudge)));$("closeBallNudge").onclick=()=>{selectedBall=null;updateBallNudge();};
    $("svgMount").addEventListener("pointerdown",event=>{const ball=event.target.closest?.(".junction-hit,.endpoint-hit");if(ball)selectBall(ball);});
  }
  function render(){
    document.documentElement.lang=ui.language; document.querySelectorAll("[data-i18n]").forEach(e=>e.textContent=tr(e.dataset.i18n)); $("releaseVersion").textContent=C.release;
    const tm=$("tableMode");tm.options[0].text=tr("large");tm.options[1].text=tr("small");tm.options[2].text=tr("both");tm.value=ui.tableMode;
    const et=$("editTable");et.options[0].text=tr("large");et.options[1].text=tr("small");et.value=ui.editTable;$("editTableControl").hidden=ui.tableMode!=="beide";
    $("languageSelect").value=ui.language; const dir=$("noseDirection");dir.options[0].text=tr("west");dir.options[1].text=tr("east");dir.value=ui.direction;
    const dep=$("departureLine");dep.options[0].text=tr("nose");dep.options[1].text=ui.language==="nl"?"Verkorte 4-bander":"Shortened four-cushion";dep.value=ui.departure;
    const cm=$("correctionMode"),cl=ui.language==="nl"?["Advies","Aan","Uit"]:["Advice","On","Off"]; $("correctionLabel").textContent=ui.language==="nl"?"Correctie":"Correction"; [...cm.options].forEach((o,i)=>o.text=cl[i]);cm.value=ui.correctionMode;$("correctionControl").hidden=ui.departure!=="kop";
    const vs=$("valueStyle"),vl=ui.language==="nl"?["Bij elk lijntje","Vervang dichtstbijzijnde nummer"]:["At each guide","Replace nearest number"];$("valueStyleLabel").textContent=ui.language==="nl"?"Stipwaarden":"Diamond values";[...vs.options].forEach((o,i)=>o.text=vl[i]);vs.value=ui.valueStyle;
    const bc=$("ballColor"),bm=$("ballMarking");$("ballColorLabel").textContent=ui.language==="nl"?"Bal":"Ball";$("ballMarkingLabel").textContent=ui.language==="nl"?"Markering":"Marking";bc.options[0].text=ui.language==="nl"?"Wit":"White";bc.options[1].text=ui.language==="nl"?"Geel":"Yellow";bm.options[0].text=ui.language==="nl"?"Met stippen":"Spotted";bm.options[1].text=ui.language==="nl"?"Zonder stippen":"Plain";bc.value=ui.ballColor;bm.value=ui.ballMarking;$("dragHelp").textContent=ui.language==="nl"?"Sleep de speelbal over de afstootlijn.":"Drag the cue ball along the departure line.";
    $("lineSelectLabel").textContent=ui.language==="nl"?"Lijn":"Line";$("patternLabel").textContent=ui.language==="nl"?"Patroon":"Pattern";$("rangeLabel").textContent=ui.language==="nl"?"Bereik":"Range";const pr=$("playRange");pr.options[0].text="LKL";pr.options[1].text=ui.language==="nl"?"Vrij spel":"Free play";pr.value=ui.playRange;
    const ps=$("patternSelect");ps.replaceChildren();C.shotLines.forEach(n=>ps.add(new Option(patternLabel(n),n)));ps.value=ui.pattern;
    const lm=$("lineOneMode");lm.options[0].text=ui.language==="nl"?"Basis":"Base";lm.options[1].text=ui.language==="nl"?"Parallel verschoven":"Parallel shift";lm.options[2].text=ui.language==="nl"?"Waaier":"Fan";lm.value=ui.lineOneMode;$("lineOneModeLabel").textContent=ui.language==="nl"?"Lijn 1":"Line 1";$("parallelOffsetLabel").textContent=ui.language==="nl"?"Parallelle lijn":"Parallel line";$("parallelOffsetControl").hidden=ui.lineOneMode!=="parallel";const bounds=parallelBounds();ui.parallelOffset=Math.max(bounds.minimum,Math.min(bounds.maximum,ui.parallelOffset));$("parallelOffset").textContent=signedOffset(ui.parallelOffset);$("parallelMinus").disabled=ui.parallelOffset<=bounds.minimum;$("parallelPlus").disabled=ui.parallelOffset>=bounds.maximum;$("fanLabel").textContent=ui.language==="nl"?"Waaierlijn":"Fan line";$("fanControl").hidden=ui.lineOneMode!=="waaier";const fs=$("fanSelect");fs.replaceChildren();C.lineOneVariants.fan.entries.forEach(x=>fs.add(new Option(x.labels[ui.language],x.key)));fs.value=ui.fanLine;
    $("exportJson").textContent=tr("myTables");$("helpText").textContent=tr("help");
    const pattern=C.patternByLine[ui.pattern]||(ui.language==="nl"?"Vrij spel":"Free play"),shownLine=lineOneName();$("editorTitle").textContent=`${pattern} · ${shownLine} · ${tableLabel(ui.editTable)}`;
    const views=ui.tableMode==="beide"?["groot","klein"]:[ui.tableMode];$("drawingTitle").textContent=`${pattern} · ${shownLine} · ${ui.direction==="west"?tr("west"):tr("east")}`;$("dragHelp").textContent=ui.language==="nl"?"Sleep een bandbal om A van de vorige en V van de volgende lijn samen te configureren. Sleep de speelbal voor de lengte van Lijn 1.":"Drag a cushion ball to configure the preceding A and following V together. Drag the cue ball to set Line 1 length.";
    renderRows();renderCorrection();renderVariantMessage();dragModels={};$("svgMount").innerHTML=views.map(drawTable).join("");bindDragBalls();bindJunctionBalls();bindEndpointBalls();updateStrokeOutput();updateBallNudge();
  }
  function selectBall(ball){selectedBall={type:ball.classList.contains("endpoint-hit")?"endpoint":"junction",table:ball.dataset.endpointTable||ball.dataset.junctionTable,part:ball.dataset.endpointPart||null,index:ball.dataset.junctionIndex!==undefined?Number(ball.dataset.junctionIndex):null,pattern:ui.pattern};updateBallNudge();}
  function updateBallNudge(){const panel=$("ballNudgePanel");if(!selectedBall||selectedBall.pattern!==ui.pattern){panel.hidden=true;return;}const lines=activeLines();if(selectedBall.type==="junction"){const previous=lines[selectedBall.index],next=lines[selectedBall.index+1];if(!previous||!next){panel.hidden=true;return;}const a=data(selectedBall.table)[previous.key].to,v=data(selectedBall.table)[next.key].from;$("selectedBallLabel").textContent=`${lineLabel(previous)} A = ${shortBand(shownBand(a.band))}${formattedValue(a.value)} · ${lineLabel(next)} V = ${shortBand(shownBand(v.band))}${formattedValue(v.value)}`;$("selectedBallValues").textContent=ui.language==="nl"?"Gedeelde bandbal":"Shared cushion ball";}else{const line=C.parts.find(x=>x.key===selectedBall.part),a=data(selectedBall.table)[selectedBall.part].to;$("selectedBallLabel").textContent=`${lineLabel(line)} A = ${shortBand(shownBand(a.band))}${formattedValue(a.value)}`;$("selectedBallValues").textContent=ui.language==="nl"?"Eindbal over de hoekzone":"End ball along corner zone";}panel.hidden=false;}
  function stepZonePoint(point,zone,delta){const direction=Math.sign(delta),count=Math.abs(delta);for(let i=0;i<count;i++){const path=zone.canonicalPath,index=path.findIndex(x=>x.band===point.band),segment=path[index]||path[0],next=Number(point.value)+direction;if(next>segment.maximum&&index<path.length-1){point.band=path[index+1].band;point.value=path[index+1].minimum;}else if(next<segment.minimum&&index>0){point.band=path[index-1].band;point.value=path[index-1].maximum;}else point.value=Math.max(segment.minimum,Math.min(segment.maximum,next));}}
  function nudgeSelected(delta){if(!selectedBall||selectedBall.pattern!==ui.pattern)return;if(selectedBall.type==="junction"){const lines=activeLines(),previous=lines[selectedBall.index],segment=data(selectedBall.table)[previous.key],maximum=(segment.to.band==="west"||segment.to.band==="oost")?80:40;segment.to.value=Math.max(0,Math.min(maximum,Math.round(Number(segment.to.value)||0)+delta));const center=bandBall(segment.to,segment.from,selectedBall.table,C.ballDiameterMm/20);updateJunction(selectedBall.table,selectedBall.index,center);}else{const point=data(selectedBall.table)[selectedBall.part].to,zone=C.partPointZones[selectedBall.part].to;stepZonePoint(point,zone,delta);save();render();}}
  function renderVariantMessage(){if(ui.lineOneMode!=="waaier"){$("messages").textContent="";return;}const fan=C.lineOneVariants.fan.entries.find(x=>x.key===ui.fanLine),line=activeLines()[0],ready=fan&&fan.between.every(n=>Number.isFinite(Number(state.data[ui.editTable]?.[n]?.[line.key]?.to?.value)));$("messages").textContent=ready?"":(ui.language==="nl"?`Vul eerst A van Lijn 1 bij ${fan.between.join(" en ")} in; HALFZES wordt niet geschat.`:`First enter Line 1 A for ${fan.between.map(patternLabel).join(" and ")}; the fan line is not estimated.`);}
  function renderRows(){
    const body=$("lineRows");body.replaceChildren();const d=data(),lines=activeLines();
    lines.forEach(line=>{const s=d[line.key],row=document.createElement("tr"),name=document.createElement("td");name.className="line-name";name.innerHTML=`<span class="line-swatch" style="background:${line.color}"></span>${lineLabel(line)}`;row.append(name);
      row.append(line.key==="neus"?fixedZCell():valueControl(line.key,"from",s.from));
      row.append(valueControl(line.key,"to",s.to));
      const c=document.createElement("td"),b=document.createElement("button");b.className="row-clear";b.textContent="×";b.onclick=()=>{clear(line.key);save();render();};c.append(b);row.append(c);body.append(row);
    });updateStatus();
  }
  function fixedZCell(){const td=document.createElement("td");td.innerHTML='<span class="fixed-z compact-z">Z</span>';return td;}
  function shortBand(b){const x={en:{west:"W",noord:"N",oost:"E",zuid:"S"},nl:{west:"W",noord:"N",oost:"O",zuid:"Z"}};return x[ui.language][b]||"—";}
  function valueControl(k,side,p){const td=document.createElement("td"),wrap=document.createElement("div"),minus=document.createElement("button"),value=document.createElement("button"),plus=document.createElement("button"),band=document.createElement("span");wrap.className="value-stepper";band.className="fixed-band";band.textContent=shortBand(shownBand(p.band));minus.type=value.type=plus.type="button";minus.textContent="−";plus.textContent="+";minus.className=plus.className="step-arrow";value.className="step-value";value.textContent=p.value??"—";minus.onclick=()=>changeValue(k,side,-1);plus.onclick=value.onclick=()=>changeValue(k,side,1);value.onkeydown=e=>{if(e.key==="ArrowLeft"||e.key==="ArrowDown"){e.preventDefault();changeValue(k,side,-1);}if(e.key==="ArrowRight"||e.key==="ArrowUp"){e.preventDefault();changeValue(k,side,1);}};wrap.append(band,minus,value,plus);td.append(wrap);return td;}
  function pointRange(k,side,forceLkl=false){const p=data()[k][side],zone=C.partPointZones?.[k]?.[side],zoneSegment=zone?.canonicalPath.find(x=>x.band===p.band),fullMax=(p.band==="west"||p.band==="oost")?80:40,useLkl=(forceLkl||ui.playRange==="lkl")&&C.patternByLine[ui.pattern]==="LKL",fallback=zoneSegment?{minimum:zoneSegment.minimum,maximum:zoneSegment.maximum}:{minimum:0,maximum:fullMax};if(!useLkl)return fallback;const code=side==="from"?"V":"A",override=C.lklValueRanges.overrides?.[ui.pattern]?.[k]?.[code];if(override)return override;const base=C.defaults?.[ui.editTable]?.[ui.pattern]?.[k]?.[side]?.value;if(!Number.isFinite(Number(base)))return fallback;const offset=C.lklValueRanges.defaultOffset[code];return{minimum:Math.max(fallback.minimum,Math.round(Number(base)-offset)),maximum:Math.min(fallback.maximum,Math.round(Number(base)+offset))};}
  function changeValue(k,side,delta){const p=data()[k][side],zone=C.partPointZones?.[k]?.[side];if(zone){const path=zone.canonicalPath,index=path.findIndex(x=>x.band===p.band),segment=path[index]||path[0],step=C.lklValueRanges.integerStep,current=Number.isFinite(Number(p.value))?Math.round(Number(p.value)):segment.minimum;let next=current+delta*step;if(next>segment.maximum&&index<path.length-1){p.band=path[index+1].band;p.value=path[index+1].minimum;}else if(next<segment.minimum&&index>0){p.band=path[index-1].band;p.value=path[index-1].maximum;}else if(next>segment.maximum&&C.lklValueRanges.wrap){p.band=path[0].band;p.value=path[0].minimum;}else if(next<segment.minimum&&C.lklValueRanges.wrap){const last=path[path.length-1];p.band=last.band;p.value=last.maximum;}else p.value=Math.max(segment.minimum,Math.min(segment.maximum,next));save();render();return;}const range=pointRange(k,side),step=C.lklValueRanges.integerStep,current=Number.isFinite(Number(p.value))?Math.round(Number(p.value)):range.minimum;let next=current+delta*step;if(C.lklValueRanges.wrap){if(next>range.maximum)next=range.minimum;if(next<range.minimum)next=range.maximum;}else next=Math.max(range.minimum,Math.min(range.maximum,next));p.value=next;save();render();}
  function bandName(b){const x={en:{west:"West",noord:"North",oost:"East",zuid:"South"},nl:{west:"West",noord:"Noord",oost:"Oost",zuid:"Zuid"}};return x[ui.language][b];}
  function clear(k){const fixed=C.fixedPartBands[k];data()[k]=k==="neus"?{from:{kind:"acquit",value:"Z"},to:{band:fixed.to,value:null}}:{from:{band:fixed.from,value:null},to:{band:fixed.to,value:null}};}
  function complete(p){return p?.kind==="acquit"||(bands.includes(p?.band)&&p.value!==null&&p.value!==""&&Number.isFinite(Number(p.value)));} function valid(p){if(p?.kind==="acquit")return true;if(!complete(p))return false;return Number(p.value)>=0&&Number(p.value)<=((p.band==="west"||p.band==="oost")?80:40);}
  function segments(t){return activeLines().filter(l=>{const s=data(t)[l.key];return complete(s.from)&&complete(s.to)&&valid(s.from)&&valid(s.to);});}
  function lklStatus(){if(C.patternByLine[ui.pattern]!=="LKL")return false;return activeLines().every(l=>["from","to"].every(side=>{const p=data()[l.key][side];if(p.kind==="acquit"||p.value===null||p.value==="")return true;const range=pointRange(l.key,side,true),v=Number(p.value);return v>=range.minimum&&v<=range.maximum;}));}
  function updateStatus(){const n=segments(ui.editTable).length,total=activeLines().length,s=$("completionStatus"),isLkl=lklStatus();if(!isLkl){ui.playRange="vrij";$("playRange").value="vrij";}s.textContent=`${n}/${total} · ${isLkl?"LKL":(ui.language==="nl"?"Vrij spel":"Free play")}`;s.classList.toggle("complete",n===total);$("patternBadge").textContent=isLkl?"LKL":(ui.language==="nl"?"Vrij spel":"Free play");$("patternBadge").classList.toggle("free",!isLkl);}
  function headCorrection(tableKey){
    const rule=C.shortenedFourCushionCorrection,head=data(tableKey).kop;
    if(!complete(head.from)||!complete(head.to)||!valid(head.from)||!valid(head.to))return null;
    const a=point(head.from,tableKey),b=point(head.to,tableKey);
    const length=Math.hypot(b.x-a.x,b.y-a.y),raw=(length-rule.headLength.referenceLengthCm)/rule.headLength.stepCm*rule.headLength.percentagePointsPerStep;
    const correction=Math.max(rule.headLength.minimumCorrectionPercentagePoints,Math.min(rule.headLength.maximumCorrectionPercentagePoints,raw));
    const effect=Math.max(rule.effectLimitsPercent.minimum,Math.min(rule.effectLimitsPercent.maximum,rule.baseEffectPercent+correction));
    return {lengthCm:Math.round(length*10)/10,correctionPercentagePoints:Math.round(correction),effectPercent:Math.round(effect)};
  }
  function renderCorrection(){
    const box=$("correctionAdvice");
    if(ui.departure!=="kop"){box.hidden=true;return;}
    box.hidden=false;
    if(ui.correctionMode==="uit"){delete state.activeEffect;box.className="correction-advice off";box.textContent=ui.language==="nl"?"Correctie uit: Kop wordt alleen volgens V en A getekend.":"Correction off: Head is drawn from V and A only.";localStorage.setItem(KEY,JSON.stringify(state));return;}
    const result=headCorrection(ui.editTable);
    if(!result){delete state.activeEffect;box.className="correction-advice";box.textContent=ui.language==="nl"?"Vul V en A van Kop volledig in voor het lengteadvies.":"Complete Head V and A to calculate the length advice.";localStorage.setItem(KEY,JSON.stringify(state));return;}
    const sign=result.correctionPercentagePoints>0?"+":"";
    if(ui.correctionMode==="aan")state.activeEffect={table:ui.editTable,pattern:ui.pattern,type:"mee-effect",...result};else delete state.activeEffect;
    box.className=`correction-advice ${ui.correctionMode==="aan"?"active":""}`;
    box.textContent=ui.language==="nl"
      ?`Kop ${result.lengthCm} cm · correctie ${sign}${result.correctionPercentagePoints} procentpunt · ${ui.correctionMode==="aan"?"actief":"advies"}: ${result.effectPercent}% mee-effect.`
      :`Head ${result.lengthCm} cm · correction ${sign}${result.correctionPercentagePoints} percentage points · ${ui.correctionMode==="aan"?"active":"advice"}: ${result.effectPercent}% running English.`;
    localStorage.setItem(KEY,JSON.stringify(state));
  }
  function point(p,t){const {widthCm:w,heightCm:h,dotOffsetCm:d}=C.tables[t];if(p.kind==="acquit")return{x:w/2,y:h*(.75-(Number(p.offset)||0)/8)};const v=Number(p.value);let q;if(p.band==="west")q={x:-d,y:(1-v/80)*h};if(p.band==="oost")q={x:w+d,y:v/80*h};if(p.band==="noord")q={x:v/40*w,y:-d};if(p.band==="zuid")q={x:(1-v/40)*w,y:h+d};return ui.direction==="oost"?{x:w-q.x,y:q.y}:q;}
  function bandBall(stip,other,t,radiusCm){
    const table=C.tables[t],a=point(stip,t),b=point(other,t),dx=b.x-a.x,dy=b.y-a.y;
    const shown=ui.direction==="oost"?mirror(stip.band):stip.band;
    let u=0;
    if(shown==="west")u=(radiusCm-a.x)/dx;else if(shown==="oost")u=(table.widthCm-radiusCm-a.x)/dx;
    else if(shown==="noord")u=(radiusCm-a.y)/dy;else if(shown==="zuid")u=(table.heightCm-radiusCm-a.y)/dy;
    return {x:a.x+u*dx,y:a.y+u*dy};
  }
  function canonicalPoint(p,t){const w=C.tables[t].widthCm;return ui.direction==="oost"?{x:w-p.x,y:p.y}:p;}
  function diamondValueThroughBall(band,ballDisplay,anchorDisplay,t){const {widthCm:w,heightCm:h,dotOffsetCm:d}=C.tables[t],ball=canonicalPoint(ballDisplay,t),anchor=canonicalPoint(anchorDisplay,t),dx=anchor.x-ball.x,dy=anchor.y-ball.y;let u,q;if(band==="west"||band==="oost"){const target=band==="west"?-d:w+d;if(Math.abs(dx)<1e-9)return null;u=(target-ball.x)/dx;q={x:target,y:ball.y+u*dy};}else{const target=band==="noord"?-d:h+d;if(Math.abs(dy)<1e-9)return null;u=(target-ball.y)/dy;q={x:ball.x+u*dx,y:target};}let value;if(band==="west")value=(1-q.y/h)*80;if(band==="oost")value=q.y/h*80;if(band==="noord")value=q.x/w*40;if(band==="zuid")value=(1-q.x/w)*40;const maximum=(band==="west"||band==="oost")?80:40,precision=C.drawing.junctionBalls.valuePrecision??1;return Math.max(0,Math.min(maximum,Math.round(value/precision)*precision));}
  function updateJunction(t,index,ballDisplay){const lines=activeLines(),previous=lines[index],next=lines[index+1];if(!previous||!next)return;const previousData=data(t)[previous.key],nextData=data(t)[next.key],a=diamondValueThroughBall(previousData.to.band,ballDisplay,point(previousData.from,t),t),v=diamondValueThroughBall(nextData.from.band,ballDisplay,point(nextData.to,t),t);if(a!==null)previousData.to.value=a;if(v!==null)nextData.from.value=v;save();render();}
  function backwardGuide(z,toward,t){
    const {widthCm:w,heightCm:h,dotOffsetCm:d}=C.tables[t],dx=z.x-toward.x,dy=z.y-toward.y,candidates=[];
    if(dx<0)candidates.push((-d-z.x)/dx);if(dx>0)candidates.push((w+d-z.x)/dx);
    if(dy<0)candidates.push((-d-z.y)/dy);if(dy>0)candidates.push((h+d-z.y)/dy);
    const u=Math.min(...candidates.filter(v=>v>0));
    return {x:z.x+u*dx,y:z.y+u*dy};
  }
  const esc=v=>String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  function formattedValue(value){const n=Number(value),text=Number.isFinite(n)?String(Math.round(n*1000)/1000):String(value);return ui.language==="nl"?text.replace(".",","):text;}
  function valueTag(p,text,color,cx,cy){
    const x=p.x,y=p.y,width=Math.max(26,text.length*6.7+12);
    return `<g class="value-tag"><rect x="${x-width/2}" y="${y-10}" width="${width}" height="20" rx="7" fill="#fffaf0" stroke="${color}" stroke-width="2"/><text x="${x}" y="${y+4}" text-anchor="middle" font-family="system-ui" font-size="11" font-weight="800" fill="#2b2118">${esc(text)}</text></g>`;
  }
  function edge(center,toward,radius){const dx=toward.x-center.x,dy=toward.y-center.y,length=Math.hypot(dx,dy)||1;return{x:center.x+dx/length*radius,y:center.y+dy/length*radius};}
  function insetEntry(from,to,t,radius){const {widthCm:w,heightCm:h}=C.tables[t],dx=to.x-from.x,dy=to.y-from.y,values=[];if(dx)values.push((radius-from.x)/dx,(w-radius-from.x)/dx);if(dy)values.push((radius-from.y)/dy,(h-radius-from.y)/dy);const valid=values.filter(u=>u>=0&&u<=1).map(u=>({u,x:from.x+u*dx,y:from.y+u*dy})).filter(p=>p.x>=radius-.001&&p.x<=w-radius+.001&&p.y>=radius-.001&&p.y<=h-radius+.001).sort((a,b)=>a.u-b.u);return valid[0]||{x:from.x,y:from.y};}
  function positionKey(t){return `${t}:${ui.pattern}:${ui.departure}:${ui.lineOneMode}:${ui.lineOneMode==="parallel"?ui.parallelOffset:ui.fanLine}`;}
  function projectionFraction(p,a,b){const dx=b.x-a.x,dy=b.y-a.y,den=dx*dx+dy*dy||1;return Math.max(0,Math.min(1,(p.x-a.x+0)*(dx)/den+(p.y-a.y)*dy/den));}
  function tagText(line,side,value){const cfg=C.drawing.valueLabels,parts=[];if(cfg.showPartName)parts.push(lineLabel(line));if(cfg.showPointType)parts.push(side);parts.push(value);return parts.join(cfg.showPartName?" · ":" ");}
  function ballSvg(p,radius,classes="",attrs=""){const style=C.drawing.balls,colors=style.colors[ui.ballColor],circleHit=["cue-ball","endpoint-ball"].includes(classes),marked=["cue-ball","junction-ball","endpoint-ball"].includes(classes),hitClass=classes==="cue-ball"?"cue-hit":"endpoint-hit",hitRadius=radius*(C.drawing.junctionBalls.touchTargetRadiusBallRadii||2.4);let svg=circleHit?`<circle class="drag-hit ${hitClass}" ${attrs} cx="${p.x}" cy="${p.y}" r="${hitRadius}" fill="transparent"/>`:"";if(marked)svg+=`<circle class="drag-halo" cx="${p.x}" cy="${p.y}" r="${radius*1.45}"/>`;svg+=`<circle class="${classes} ball-visible" cx="${p.x}" cy="${p.y}" r="${radius}" fill="${colors.fill}" stroke="${style.outline}" stroke-width="${style.outlineWidthSvg}"/>`;if(ui.ballMarking==="spotted"){const sr=Math.max(1.3,radius*.18);svg+=`<circle pointer-events="none" cx="${p.x-radius*.28}" cy="${p.y-radius*.22}" r="${sr}" fill="${colors.spot}"/><circle pointer-events="none" cx="${p.x+radius*.3}" cy="${p.y+radius*.2}" r="${sr*.75}" fill="${colors.spot}"/>`;}return svg;}
  function suppressedDots(t){
    const hidden=new Set();if(ui.valueStyle!=="vervang_dichtstbijzijnde_nummer")return hidden;
    activeLines().forEach(l=>{const seg=data(t)[l.key];[seg.from,seg.to].forEach(p=>{if(p.kind==="acquit"||!complete(p)||!valid(p))return;const band=shownBand(p.band),max=(band==="west"||band==="oost")?80:40,nearest=Math.max(0,Math.min(max,Math.round(Number(p.value)/10)*10));hidden.add(`${band}:${nearest}`);});});
    return hidden;
  }
  function drawTable(t){
    const table=C.tables[t],W=510,H=850,fieldW=340,fieldH=680,scale=fieldW/table.widthCm,d=table.dotOffsetCm*scale,x=(W-fieldW)/2,y=90,wood=d+14,map=p=>({x:x+p.x*scale,y:y+p.y*scale}),segs=segments(t);let s=`<svg class="table-svg" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" role="img" aria-label="${esc(lineOneName())} ${esc(tableLabel(t))}"><rect width="${W}" height="${H}" rx="18" fill="#f7f1e5"/><text x="${W/2}" y="28" text-anchor="middle" font-family="system-ui" font-size="20" font-weight="800" fill="#2b2118">${esc(lineOneName())} · ${esc(tableLabel(t).toUpperCase())}</text><text x="${W/2}" y="49" text-anchor="middle" font-family="system-ui" font-size="11" fill="#6d5d4b">${table.widthCm} × ${table.heightCm} cm · 9.5 cm</text><rect x="${x-wood}" y="${y-wood}" width="${fieldW+2*wood}" height="${fieldH+2*wood}" rx="11" fill="#704725" stroke="#3a2516" stroke-width="3"/><rect x="${x}" y="${y}" width="${fieldW}" height="${fieldH}" fill="#176f4f" stroke="#e7c66e" stroke-width="3"/>`;
    s+=dots(t,map,suppressedDots(t));
    const active=activeLines(),junctionCenters={};segs.forEach(l=>{const index=active.findIndex(x=>x.key===l.key);
      const seg=variantSegment(t,l,index);if(!complete(seg.from)||!complete(seg.to)||!valid(seg.from)||!valid(seg.to))return;const radiusCm=C.ballDiameterMm/20,stipA=point(seg.from,t),stipB=point(seg.to,t);
      const fixedA=junctionCenters[index]||(seg.from.kind==="acquit"?stipA:bandBall(seg.from,seg.to,t,radiusCm)),ballB=bandBall(seg.to,seg.from,t,radiusCm);junctionCenters[index+1]=ballB;
      const guideA=seg.from.kind==="acquit"?backwardGuide(fixedA,ballB,t):stipA,isDeparture=index===0;
      const startLimit=isDeparture?insetEntry(guideA,ballB,t,radiusCm):fixedA,startDistance=Math.hypot(ballB.x-startLimit.x,ballB.y-startLimit.y);
      const defaultFraction=seg.from.kind==="acquit"?projectionFraction(fixedA,startLimit,ballB):0,key=positionKey(t);
      const maxFraction=Math.max(0,1-(2*radiusCm+C.drawing.departureBall.minimumGapBallDiameters*radiusCm*2)/(startDistance||1));
      const fraction=isDeparture?Math.max(0,Math.min(maxFraction,state.departurePositions[key]??defaultFraction)):0;
      const ballA=isDeparture?{x:startLimit.x+(ballB.x-startLimit.x)*fraction,y:startLimit.y+(ballB.y-startLimit.y)*fraction}:fixedA;
      const A=map(ballA),B=map(ballB),GA=map(guideA),GB=map(stipB),ballRadius=radiusCm*scale,lineWidth=C.ballDiameterMm/10*scale,guideWidth=C.drawing.guideLineWidthSvg,mx=(A.x+B.x)/2,my=(A.y+B.y)/2;
      const thinA=edge(A,GA,ballRadius),thickA=edge(A,B,ballRadius),thickB=edge(B,A,ballRadius),thinB=edge(B,GB,ballRadius);
      const fromValue=seg.from.kind==="acquit"?seg.from.value:formattedValue(seg.from.value),toValue=formattedValue(seg.to.value);
      const fromTag=tagText(l,"V",fromValue),toTag=tagText(l,"A",toValue),lengthCm=Math.max(0,startDistance*(1-fraction)-radiusCm*2);
      if(isDeparture)dragModels[t]={startDistance,radiusCm,fraction,maxFraction,lengthCm};
      const dragAttrs=isDeparture?`tabindex="0" role="slider" aria-label="${ui.language==="nl"?"Lijn 1 afstootlengte":"Line 1 stroke length"}" data-drag-table="${t}" data-x0="${map(startLimit).x}" data-y0="${map(startLimit).y}" data-x1="${B.x}" data-y1="${B.y}" data-max="${maxFraction}"`:"";
      const nextLine=active[index+1],previousLine=active[index-1],junction=nextLine&&ui.lineOneMode==="basis"&&data(t)[nextLine.key].from.band===seg.to.band,endpointZone=!nextLine&&C.partPointZones?.[l.key]?.to,priorJunction=previousLine&&ui.lineOneMode==="basis"&&data(t)[previousLine.key].to.band===seg.from.band&&complete(data(t)[previousLine.key].to),junctionAttrs=junction?`tabindex="0" role="slider" aria-label="${esc(lineLabel(l))} A · ${esc(lineLabel(nextLine))} V" data-junction-table="${t}" data-junction-index="${index}" data-junction-band="${shownBand(seg.to.band)}"`:"",endpointAttrs=endpointZone?`tabindex="0" role="slider" aria-label="${esc(lineLabel(l))} A" data-endpoint-table="${t}" data-endpoint-part="${l.key}"`:"";
      const fromTagPoint=seg.from.kind==="acquit"?map(stipA):GA,nextV=junction?map(point(data(t)[nextLine.key].from,t)):null,pad=C.drawing.junctionBalls.clickZone.paddingSvg,junctionZone=junction?`<rect class="drag-hit junction-hit junction-click-zone" ${junctionAttrs} x="${Math.min(B.x,GB.x,nextV.x)-pad}" y="${Math.min(B.y,GB.y,nextV.y)-pad}" width="${Math.max(B.x,GB.x,nextV.x)-Math.min(B.x,GB.x,nextV.x)+2*pad}" height="${Math.max(B.y,GB.y,nextV.y)-Math.min(B.y,GB.y,nextV.y)+2*pad}" rx="12"/>`:"";
      s+=`<g data-part="${l.key}"><line x1="${GA.x}" y1="${GA.y}" x2="${thinA.x}" y2="${thinA.y}" stroke="${l.color}" stroke-width="${guideWidth}"/><line x1="${thickA.x}" y1="${thickA.y}" x2="${thickB.x}" y2="${thickB.y}" stroke="${l.color}" stroke-width="${lineWidth}"/><line x1="${thinB.x}" y1="${thinB.y}" x2="${GB.x}" y2="${GB.y}" stroke="${l.color}" stroke-width="${guideWidth}"/>${junctionZone}${priorJunction?"":ballSvg(A,ballRadius,isDeparture?"cue-ball":"",dragAttrs)}${ballSvg(B,ballRadius,junction?"junction-ball":endpointZone?"endpoint-ball":"",junction?junctionAttrs:endpointAttrs)}<text x="${mx}" y="${my-10}" text-anchor="middle" font-family="system-ui" font-size="12" font-weight="800" fill="#fff6dd" stroke="#103d2c" stroke-width="3" paint-order="stroke fill">${esc(lineLabel(l))}</text>${isDeparture?`<text x="${mx}" y="${my+18}" text-anchor="middle" font-family="system-ui" font-size="11" font-weight="800" fill="#fff6dd" stroke="#103d2c" stroke-width="3" paint-order="stroke fill">${ui.language==="nl"?"Afstoot":"Stroke"} ${Math.round(lengthCm)} cm</text>`:""}${valueTag(fromTagPoint,fromTag,l.color,x+fieldW/2,y+fieldH/2)}${valueTag(GB,toTag,l.color,x+fieldW/2,y+fieldH/2)}</g>`;
    });
    s+=`<text x="${W/2}" y="${H-17}" text-anchor="middle" font-family="system-ui" font-size="11" fill="#6d5d4b">${segs.length===activeLines().length?tr("complete"):`${segs.length}/${activeLines().length} ${tr("lines")}`}</text></svg>`;return `<div class="drawing-card">${s}</div>`;
  }
  function startBallDrag(){document.body.classList.add("ball-dragging");}
  function stopBallDrag(){document.body.classList.remove("ball-dragging");}
  function bindDragBalls(){
    document.querySelectorAll(".cue-hit").forEach(ball=>{ball.addEventListener("keydown",event=>{if(event.key==="ArrowLeft"||event.key==="ArrowDown"){event.preventDefault();adjustStroke(-C.drawing.departureBall.precisionStepCm,ball.dataset.dragTable);}if(event.key==="ArrowRight"||event.key==="ArrowUp"){event.preventDefault();adjustStroke(C.drawing.departureBall.precisionStepCm,ball.dataset.dragTable);}});ball.addEventListener("pointerdown",event=>{
      event.preventDefault();event.stopPropagation();startBallDrag();const table=ball.dataset.dragTable;
      const move=ev=>{ev.preventDefault();const current=document.querySelector(`.cue-hit[data-drag-table="${table}"]`);if(!current)return;const svg=current.closest("svg"),matrix=svg.getScreenCTM();if(!matrix)return;const p=new DOMPoint(ev.clientX,ev.clientY).matrixTransform(matrix.inverse()),x0=Number(current.dataset.x0),y0=Number(current.dataset.y0),x1=Number(current.dataset.x1),y1=Number(current.dataset.y1),dx=x1-x0,dy=y1-y0,den=dx*dx+dy*dy||1,max=Number(current.dataset.max),fraction=Math.max(0,Math.min(max,((p.x-x0)*dx+(p.y-y0)*dy)/den));state.departurePositions[positionKey(table)]=fraction;localStorage.setItem(KEY,JSON.stringify(state));render();};
      const up=()=>{document.removeEventListener("pointermove",move);document.removeEventListener("pointerup",up);document.removeEventListener("pointercancel",up);stopBallDrag();save();};
      document.addEventListener("pointermove",move,{passive:false});document.addEventListener("pointerup",up,{once:true});document.addEventListener("pointercancel",up,{once:true});
    });});
  }
  function bindJunctionBalls(){document.querySelectorAll(".junction-hit").forEach(ball=>ball.addEventListener("pointerdown",event=>{event.preventDefault();event.stopPropagation();startBallDrag();const table=ball.dataset.junctionTable,index=Number(ball.dataset.junctionIndex);const move=ev=>{ev.preventDefault();const current=document.querySelector(`.junction-hit[data-junction-table="${table}"][data-junction-index="${index}"]`);if(!current)return;const shown=current.dataset.junctionBand,svg=current.closest("svg"),matrix=svg?.getScreenCTM();if(!matrix)return;const p=new DOMPoint(ev.clientX,ev.clientY).matrixTransform(matrix.inverse()),cfg=C.tables[table],fieldW=340,fieldH=680,scale=fieldW/cfg.widthCm,x=(510-fieldW)/2,y=90,radius=C.ballDiameterMm/20;let cm={x:(p.x-x)/scale,y:(p.y-y)/scale};if(shown==="west")cm={x:radius,y:Math.max(radius,Math.min(cfg.heightCm-radius,cm.y))};if(shown==="oost")cm={x:cfg.widthCm-radius,y:Math.max(radius,Math.min(cfg.heightCm-radius,cm.y))};if(shown==="noord")cm={x:Math.max(radius,Math.min(cfg.widthCm-radius,cm.x)),y:radius};if(shown==="zuid")cm={x:Math.max(radius,Math.min(cfg.widthCm-radius,cm.x)),y:cfg.heightCm-radius};updateJunction(table,index,cm);};const up=()=>{document.removeEventListener("pointermove",move);document.removeEventListener("pointerup",up);document.removeEventListener("pointercancel",up);stopBallDrag();};document.addEventListener("pointermove",move,{passive:false});document.addEventListener("pointerup",up,{once:true});document.addEventListener("pointercancel",up,{once:true});}));}
  function bindEndpointBalls(){document.querySelectorAll(".endpoint-hit").forEach(ball=>ball.addEventListener("pointerdown",event=>{event.preventDefault();event.stopPropagation();startBallDrag();const table=ball.dataset.endpointTable,part=ball.dataset.endpointPart;const move=ev=>{ev.preventDefault();const current=document.querySelector(`.endpoint-hit[data-endpoint-table="${table}"][data-endpoint-part="${part}"]`);if(!current)return;const svg=current.closest("svg"),matrix=svg?.getScreenCTM();if(!matrix)return;const p=new DOMPoint(ev.clientX,ev.clientY).matrixTransform(matrix.inverse()),cfg=C.tables[table],fieldW=340,scale=fieldW/cfg.widthCm,x=(510-fieldW)/2,y=90,radius=C.ballDiameterMm/20,raw={x:(p.x-x)/scale,y:(p.y-y)/scale},segment=data(table)[part],anchor=point(segment.from,table),zone=C.partPointZones[part].to,candidates=zone.canonicalPath.map(path=>{const shown=shownBand(path.band);let trial;if(shown==="noord")trial={x:Math.max(radius,Math.min(cfg.widthCm-radius,raw.x)),y:radius};else if(shown==="oost")trial={x:cfg.widthCm-radius,y:Math.max(radius,Math.min(cfg.heightCm-radius,raw.y))};else if(shown==="west")trial={x:radius,y:Math.max(radius,Math.min(cfg.heightCm-radius,raw.y))};else trial={x:Math.max(radius,Math.min(cfg.widthCm-radius,raw.x)),y:cfg.heightCm-radius};let value=diamondValueThroughBall(path.band,trial,anchor,table);value=Math.max(path.minimum,Math.min(path.maximum,value??path.minimum));const center=bandBall({band:path.band,value},segment.from,table,radius);return{band:path.band,value,center,distance:Math.hypot(center.x-raw.x,center.y-raw.y)};}).sort((a,b)=>a.distance-b.distance),chosen=candidates[0];segment.to.band=chosen.band;segment.to.value=chosen.value;save();render();};const up=()=>{document.removeEventListener("pointermove",move);document.removeEventListener("pointerup",up);document.removeEventListener("pointercancel",up);stopBallDrag();};document.addEventListener("pointermove",move,{passive:false});document.addEventListener("pointerup",up,{once:true});document.addEventListener("pointercancel",up,{once:true});}));}
  function adjustStroke(deltaCm,table=ui.editTable){const model=dragModels[table];if(!model)return;const key=positionKey(table),next=Math.max(0,Math.min(model.maxFraction,model.fraction-deltaCm/model.startDistance));state.departurePositions[key]=next;save();render();}
  function updateStrokeOutput(){const model=dragModels[ui.editTable]||dragModels[ui.tableMode];$("strokeLength").textContent=model?`${Math.round(model.lengthCm)} cm`:"— cm";$("strokeMinus").disabled=$("strokePlus").disabled=!model;}
  function displayPoint(b,v,t){return point({band:ui.direction==="oost"?mirror(b):b,value:v},t);}
  function dots(t,map,hidden){let c='<g fill="#fff8dc" stroke="#3b291c" stroke-width=".8">',l='<g fill="#fff8dc" stroke="#4b301d" stroke-width="3" paint-order="stroke fill" font-family="system-ui" font-size="14" font-weight="800">';["west","oost"].forEach(b=>{for(let v=0;v<=80;v+=10){const p=map(displayPoint(b,v,t));c+=`<circle cx="${p.x}" cy="${p.y}" r="4"/>`;if(!hidden.has(`${b}:${v}`))l+=`<text x="${p.x+(b==="west"?-13:13)}" y="${p.y+5}" text-anchor="${b==="west"?"end":"start"}">${v}</text>`;}});["noord","zuid"].forEach(b=>{for(let v=0;v<=40;v+=10){const p=map(displayPoint(b,v,t));c+=`<circle cx="${p.x}" cy="${p.y}" r="4"/>`;if(!hidden.has(`${b}:${v}`))l+=`<text x="${p.x}" y="${p.y+(b==="noord"?-13:23)}" text-anchor="middle">${v}</text>`;}});return c+'</g>'+l+'</g>';}
  function download(name,content,type){const blob=new Blob([content],{type}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
  function exportSvg(){const svgs=[...document.querySelectorAll(".table-svg")];svgs.forEach((s,i)=>download(`3B-${ui.tableMode==="beide"?(i?"small":"large"):ui.tableMode}-${ui.pattern}.svg`,new XMLSerializer().serializeToString(s),"image/svg+xml"));}
  function exportJson(){download(ui.language==="nl"?"3B-mijn-tafels.json":"3B-my-tables.json",JSON.stringify(state,null,2),"application/json");}
  async function importJson(e){const f=e.target.files[0];if(!f)return;try{const x=JSON.parse(await f.text());if(!x?.data)throw Error("Invalid file");state.data=x.data;state.departurePositions=x.departurePositions||{};if(x.ui)Object.assign(ui,x.ui);normalize();save();render();}catch(err){$("messages").textContent=err.message;}e.target.value="";}
  function reset(){if(!confirm(`${tr("confirm")} ${patternLabel(ui.pattern)} · ${tableLabel(ui.editTable)}?`))return;state.data[ui.editTable][ui.pattern]=blank();delete state.departurePositions[`${ui.editTable}:${ui.pattern}:neus`];delete state.departurePositions[`${ui.editTable}:${ui.pattern}:kop`];save();render();}
  init();
})();
